#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := irrigation_ctrl

CFLAGS += -DCONFIG_MONGOOSE_PRESENT -DMG_ENABLE_HTTP_STREAMING_MULTIPART -DMG_ENABLE_FILESYSTEM -DMG_DISABLE_DIRECTORY_LISTING=1 -DMG_DISABLE_DAV=1 -DMG_DISABLE_CGI=1
CXXFLAGS += -DCONFIG_MONGOOSE_PRESENT -DMG_ENABLE_HTTP_STREAMING_MULTIPART -DMG_ENABLE_FILESYSTEM -DMG_DISABLE_DIRECTORY_LISTING=1 -DMG_DISABLE_DAV=1 -DMG_DISABLE_CGI=1

include $(IDF_PATH)/make/project.mk

MONITOR_OPTS += --eol CRLF

.PHONY: doc
doc:
	doxygen doc/Doxyfile
